# Generated by Django 3.0 on 2019-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='querydata',
            fields=[
                ('Sno', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
