# Generated by Django 3.0 on 2020-01-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmusweb', '0002_auto_20200121_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='querydata',
        ),
    ]
