# Generated by Django 3.0 on 2020-01-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadmusweb', '0003_delete_querydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='querydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
