# Generated by Django 3.0 on 2020-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadmusweb', '0004_querydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='querydata',
        ),
    ]
